set(PACKAGE_VERSION 0.7.1)

string(REGEX MATCH "^[0-9]+" PACKAGE_VERSION_MAJOR "${PACKAGE_VERSION}")

# same semantics as write_basic_package_version_file(COMPATIBILITY SameMajorVersion)
if(PACKAGE_FIND_VERSION VERSION_GREATER PACKAGE_VERSION
        OR NOT PACKAGE_FIND_VERSION_MAJOR EQUAL PACKAGE_VERSION_MAJOR)
    set(PACKAGE_VERSION_UNSUITABLE TRUE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
